### ISSUE TITLE
Crash when calling markdownToHTML on an empty string

### ISSUE THREAD

**Issue by rivera-ernesto** [PerfectlySoft/Perfect-Markdown#3]
This crashes the library:

```swift
let string = ""
let html = string.markdownToHTML
```

Ideally `markdownToHTML` should return `""` but I am not sure where that fix should be done.

**Comment by wito** [comment]
This should be resolved in #4.

**Comment by RockfordWei** [comment]
Thanks for the contribution 👍 @rivera-ernesto @wito
